name: Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '1.22.0'
          cache: false
      - name: Notify
        working-directory: script
        run: |
          go mod download
          go run main.go
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          OPENAI_PROMPT: ${{ secrets.OPENAI_PROMPT }}
          IMAGE_THUMBNAIL_URL: ${{ secrets.IMAGE_THUMBNAIL_URL }}
          IMAGE_FULLSIZE_URL: ${{ secrets.IMAGE_FULLSIZE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
