name: Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

env:
  FIRST_RUN_DATE: 2024-02-14
  CYCLE: 28
  DAYS_OF_PILL: 21

jobs:
  calculate-days:
    runs-on: ubuntu-latest
    outputs:
      is_holiday: ${{ steps.calculate.outputs.is_holiday }}
    steps:
      - name: Calculate
        id: calculate
        run: |
          current_date=$(date +%Y-%m-%d)
          start=$(date -d ${{ env.FIRST_RUN_DATE }} +%s)
          end=$(date -d $current_date +%s)
          daydiff=$(((end-start) / 60 / 60 / 24 ))
          if [[ $((daydiff % 28 - 21 )) -le 0 ]]; then
            echo "is_holiday=false" >> "$GITHUB_OUTPUT"
          else
            echo "is_holiday=true" >> "$GITHUB_OUTPUT"
          fi
  notify:
    runs-on: ubuntu-lates
    if: ${{ needs.calculate-days.outputs.is_holiday }} 
    needs:
      - calculate-days
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
          cache: false
      - name: Notify
        working-directory: script
        run: |
          go mod download
          go run main.go
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          OPENAI_PROMPT: ${{ secrets.OPENAI_PROMPT }}
          IMAGE_URL: ${{ secrets.IMAGE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
