name: Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

env:
  TZ: 'Asia/Tokyo'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
          cache: false
      - name: Notify
        working-directory: script
        run: |
          go mod download
          go run main.go
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          OPENAI_PROMPT: ${{ secrets.OPENAI_PROMPT }}
          IMAGE_URL: ${{ secrets.IMAGE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIRST_RUN_DATE: 2024-02-14
