name: Notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

env:
  TZ: 'Asia/Tokyo'
  LINE_TOKEN: ${{ secrets.LINE_TOKEN }}

jobs:
  notify:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.22.0'
          cache: false
      - name: Notify
        working-directory: script
        run: |
          go mod download
          go run main.go
        env:
          OPENAI_PROMPT: ${{ secrets.OPENAI_PROMPT }}
          IMAGE_URL: ${{ secrets.IMAGE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIRST_RUN_DATE: 2024-02-14
      - name: Notify if failed
        if: failure()
        run: |
          curl -X POST -H "Authorization: Bearer ${{ env.LINE_TOKEN }}" \
            -F 'message=workflowが失敗しました。原因を確認してください。${{ env.WORKFLOW_URL }}' \
            ${{ env.ENDPOINT }}
        env:
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          ENDPOINT: https://notify-api.line.me/api/notify
